apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web
    owner: team-a
    website: production
    country: TN
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 8083