apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
data:
  password: bXlzcWxfcGFzc3dvcmQ=  # base64 encoded value of 'mysql_password'
---
apiVersion: v1
kind: Service 
metadata:
  name: db-mysql
  labels:
    app: db-mysql
spec:
  type: ClusterIP
  selector:
    app: db-mysql
  ports:
    - port: 3306
      protocol: TCP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-mysql
spec:
  selector:
    matchLabels:
      app: db-mysql
  serviceName: "db-mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: db-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: mydatabase
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimsTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"  
      resources:
        requests:
          storage: 1Gi