apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  volumes:
    - name: storage-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
          name: webserver
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: server-volume