apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: ZGJfdXNlcg==  # base64 encoded value of 'db_user'
  password: c2VjdXJlX3Bhc3N3b
StringData:
  server: database-server