apiVersion: v1
kind: Secret
metadata:
  name: db-secret-un
type: Opaque
StringData:
  config.yaml: |
    ytchannel: "https://www.youtube.com/c/TechWorldwithNana"
    username: "db_user"
    password: "secure_passw"