apiVersion: v1
kind: Pod 
metadata:
  name: env-server-user-secret
spec:
  containers:
    - name: envvar-container 
      image: nginx
      env:
        - name: SERVER_USER
          valueFrom:
            secretKeyRef:
              name: server-user
              key: username