apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis:6.0
# volume of container
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
# volume of pod
  volumes:
  - name: redis-storage
